replicaCount: 2

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

image:
  repository: reactapp.azurecr.io/angular-aks-app
  tag: v1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

containerPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: angular.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

livenessProbe:
  path: /
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
