replicaCount: 2
revisionHistoryLimit: 3
progressDeadlineSeconds: 900
minReadySeconds: 0
terminationGracePeriodSeconds: 10

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

image:
  repository: reactapp.azurecr.io/angular-aks-app
  tag: v1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

containerPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: angular.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

livenessProbe:
  path: /
  initialDelaySeconds: 20
  periodSeconds: 10

startupProbe:
  enabled: true
  path: /
  initialDelaySeconds: 0
  periodSeconds: 5
  failureThreshold: 24

readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
