replicaCount: 1

image:
  repository: reactapp.azurecr.io/angular-aks-app
  tag: v6
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

containerPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: angular.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

livenessProbe:
  path: /
  initialDelaySeconds: 30
  periodSeconds: 15

readinessProbe:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 15
