name: CI Security and Quality

on:
  workflow_dispatch:

# on:
#   pull_request:
#   push:
#     branches:
#       - main

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/reusable-ci-security.yml
    with:
      project_directory: angular-aks-github
      node_version: '20'
      scan_severity: HIGH,CRITICAL
      enable_sonar: true
      runner_labels: '["self-hosted","Linux","X64"]'
    secrets: inherit



  
