name: Deploy Angular to AKS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Docker image tag
        required: true
        default: v6
        type: string
      replica_count:
        description: Number of pods
        required: true
        default: '1'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-scan-deploy:
    uses: ./.github/workflows/reusable-deploy-aks.yml
    with:
      project_directory: angular-aks-github
      environment_name: dev
      image_tag: ${{ inputs.image_tag }}
      replica_count: ${{ inputs.replica_count }}
      node_version: '20'
      docker_platform: linux/amd64
      helm_chart_path: ./helm/angular-aks
      helm_values_file: ./helm/angular-aks/values-delphi.yaml
      app_smoke_path: /
      lb_poll_attempts: 30
      scan_severity: HIGH,CRITICAL
      enable_sonar: true
      runner_labels: '["self-hosted","Linux","X64"]'
    secrets: inherit
